---
deployment:
  tasks:
    - /usr/bin/git -C /home2/jairoant/public_html fetch origin
    - /usr/bin/git -C /home2/jairoant/public_html checkout -f production
    - /usr/bin/git -C /home2/jairoant/public_html reset --hard origin/production
