name: Deploy a HostGator

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull desde GitHub a cPanel
        run: |
          curl -s -k \
            -H "Authorization: cpanel ${{ secrets.CPANEL_USER }}:${{ secrets.CPANEL_PASS }}" \
            "https://sh00004.hostgator.cl:2083/execute/VersionControl/update" \
            --data-urlencode "repository_root=/home2/jairoant/public_html"

      - name: Deploy en cPanel
        run: |
          curl -s -k \
            -H "Authorization: cpanel ${{ secrets.CPANEL_USER }}:${{ secrets.CPANEL_PASS }}" \
            "https://sh00004.hostgator.cl:2083/execute/VersionControlDeployment/create" \
            --data-urlencode "repository_root=/home2/jairoant/public_html"
